import {
    Wind,
    Bell,
    CloudRain,
    Star,
    TreePine,
    Moon,
    Sun,
    Target,
    Coffee,
    Sparkles,
    Zap,
    Leaf,
    Play,
    Pause,
    Volume2,
    Music,
    Lock,
    Menu,
    Utensils,
    Flower2,
    Soup,
    Flame,
    ChevronDown,
    ChevronUp,
    RotateCcw,
    Clock,
    CheckCircle,
    Eye,
    X,
    LucideProps,
    // New Icons
    Droplet,
    Waves,
    Rocket,
    Bug,
    TreeDeciduous,
    Music2,
    Bird,
    Building2,
    Ship,
    Droplets,
    Disc,
    Snowflake,
    Orbit,
    Train,
    Umbrella,
    GlassWater,
    Tornado,
    ThermometerSnowflake,
    Anchor,
    Compass,
    Piano,
    Brain,
    Tent,
    Ghost,
    Headphones,
    Sunset,
    Smile,
    Cherry,
    BellRing,
    CloudLightning,
    Quote,
    Github,
    Twitter,
    Instagram,
    ArrowUp,
    Facebook,
    AlertTriangle,
    User,
    Crown,
    ShieldCheck,
    LogOut,
    Save,
    Trash2,
    XCircle,
    CloudDrizzle,
    BedDouble,
    Infinity,
    Mountain,
    Activity,
    LandPlot // For Zen Garden alternative if needed, but Flower2 is good.
} from 'lucide-react';

const XBrandIcon = ({ className, ...props }: any) => (
    <svg viewBox="0 0 24 24" fill="currentColor" className={className} {...props}>
        <path d="M18.901 1.153h3.68l-8.04 9.19L24 22.846h-7.406l-5.8-7.584-6.638 7.584H.474l8.6-9.83L0 1.154h7.594l5.243 6.932ZM17.61 20.644h2.039L6.486 3.24H4.298Z" />
    </svg>
);

const iconMap: Record<string, IconType | React.FC<any>> = {
    // Existing
    Waves: Waves,
    Bell,
    Wind,
    CloudRain,
    Stars: Star,
    Trees: TreePine,
    Focus: Target,
    Meditate: Sparkles,
    Sleep: Moon,
    Nature: Leaf,
    Night: Moon,
    Cosmos: Star,
    Rain: CloudRain,
    All: Zap,
    Play,
    Pause,
    Volume2,
    Sun,
    Moon,
    Music,
    Lock,
    Flame,
    Free: Leaf,
    Premium: Star,
    Fireplace: Flame,
    Restaurant: Utensils,
    Japan: Flower2,
    JapaneseLantern: Flower2,
    ChevronDown,
    ChevronUp,
    RotateCcw,
    Clock,
    CheckCircle,
    Eye,
    X,
    Menu,
    Soup,
    Quote,
    Github,
    Twitter,
    Instagram,
    ArrowUp,
    Facebook,
    User,
    "BrandX": XBrandIcon,

    // New Mappings
    Droplet,
    Rocket,
    Bug,
    TreeDeciduous,
    Music2,
    Bird,
    Building2,
    Ship,
    Droplets,
    Disc,
    Snowflake,
    Orbit,
    Train,
    Umbrella,
    GlassWater,
    Tornado,
    ThermometerSnowflake,
    Anchor,
    Compass,
    Piano,
    Brain,
    Tent,
    Ghost,
    Headphones,
    Sunset,
    Smile,
    Cherry,
    BellRing,
    Sparkles,
    Thunder: CloudLightning,
    Zap: Zap,
    Star: Star,
    Crown,
    ShieldCheck,
    LogOut,
    Save,
    Trash2,
    XCircle,
    AlertTriangle,
    CloudDrizzle,
    BedDouble,
    Infinity,
    Mountain,
    Activity,
    Flower2, // Explicit mapping for Zen Garden
    LandPlot,
};

export const Icon = ({ name, className, strokeWidth = 1.5 }: { name: string; className?: string, strokeWidth?: number }) => {
    const LucideIcon = iconMap[name] || Music;
    return <LucideIcon className={className} strokeWidth={strokeWidth} />;
};
